nelmio_cors:
    defaults:
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
