controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
minha_rota:
    path: /minha-rota
    controller: App\Controller\MeuController::minhaAcao
Beaches:
    path: /beaches
    controller: App\Controller\BeachController::listBeaches
